///////////////////////////////////////////////////////////////////////////////
// KinematicClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "KinematicClassFactory.h"
#include "KinematicServices.h"
#include "KinematicVersion.h"
#include "KineModule.h"

BEGIN_CLASS_MAP(CKinematicClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_KinematicCKineModule, SRVNAME_KINEMATIC "!CKineModule", CKineModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CKinematicClassFactory::CKinematicClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_KINEMATIC)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(Kinematic));
#endif //defined(TCDBG_UNIT_VERSION)
}

