///////////////////////////////////////////////////////////////////////////////
// KinematicInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "KinematicServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
