<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="MAIN" Id="{5df62128-f8ca-4cb2-82f0-fb5ed1ffd77a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
bChangeSeparatorToComma	: BOOL := TRUE;
P_TextModeWrite_WriteTrigger:BOOL:=FALSE;
P_TextModeWrite_WriteFilePath:T_MaxString := 'C:\Users\Administrator\Desktop\Pos.csv';
P_TextModeRead_ReadTrigger:BOOL:=FALSE;
P_TextModeRead_ReadFilePath:T_MaxString := 'C:\Users\Administrator\Desktop\Pos.csv';

CurrentJob: INT:= 0;//Job Code
CurrentJobState:STRING(80);//Say in which state

LAMP:BOOL;
POWER:BOOL;
Move_AB:BOOL;

SetPointGenEnable:ARRAY [0..5] OF MC_ExtSetPointGenEnable;
SetpointGenDisable:ARRAY [0..5] OF MC_ExtSetpointGenDisable;
SetPointGenEnable_output: ARRAY [0..5] OF ST_McOutputs;
SetPointGenDisable_output: ARRAY [0..5] OF ST_McOutputs;
enable:ARRAY [0..5] OF BOOL;
disable:ARRAY [0..5] OF BOOL;

position:ARRAY [0..5] OF LREAL;
velocity:ARRAY [0..5] OF LREAL;
direction:ARRAY [0..5] OF DINT;
acceleration:ARRAY [0..5] OF LREAL;

END_VAR
VAR CONSTANT
	GlobalSetSpeed : ARRAY[0..5]OF LREAL:=[3200,3200,3200,3200,3200,3200];
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF bChangeSeparatorToComma THEN
	DEFAULT_CSV_FIELD_SEP := 16#2C;(* Comma ASCII code *)
ELSE
	DEFAULT_CSV_FIELD_SEP := 16#3B;(* Semicolon ASCII code *)
END_IF

GVL.OutActPos[0]:=GVL.Axis[0].NcToPlc.ActPos;
GVL.OutActPos[1]:=-GVL.Axis[1].NcToPlc.ActPos;
GVL.OutActPos[2]:=GVL.Axis[2].NcToPlc.ActPos;
GVL.OutActPos[3]:=GVL.Axis[3].NcToPlc.ActPos;
GVL.OutActPos[4]:=GVL.Axis[4].NcToPlc.ActPos;
GVL.OutActPos[5]:=GVL.Axis[5].NcToPlc.ActPos;
GVL.OutMovePos[0]:=STRING_TO_LREAL(GVL.OutMovePosString[0]);
GVL.OutMovePos[1]:=STRING_TO_LREAL(GVL.OutMovePosString[1]);
GVL.OutMovePos[2]:=STRING_TO_LREAL(GVL.OutMovePosString[2]);
GVL.MoveA[0]:=STRING_TO_LREAL(GVL.MoveAString[0])*24.995;
GVL.MoveA[1]:=STRING_TO_LREAL(GVL.MoveAString[1])*32.28;
GVL.MoveA[2]:=STRING_TO_LREAL(GVL.MoveAString[2])*49.845;
GVL.MoveA[3]:=STRING_TO_LREAL(GVL.MoveAString[3])*50.905;
GVL.MoveA[4]:=STRING_TO_LREAL(GVL.MoveAString[4])*80.34;
GVL.MoveA[5]:=STRING_TO_LREAL(GVL.MoveAString[5])*60.5;


CASE CurrentJob OF	
	0://None state
		AxisStopTrigger[0]:=FALSE;AxisStopTrigger[1]:=FALSE;AxisStopTrigger[2]:=FALSE;
		AxisStopTrigger[3]:=FALSE;AxisStopTrigger[4]:=FALSE;AxisStopTrigger[5]:=FALSE;
		AxisStop();//失能功能块
		
		JogFw[0]:=FALSE;JogFw[1]:=FALSE;JogFw[2]:=FALSE;JogFw[3]:=FALSE;JogFw[4]:=FALSE;JogFw[5]:=FALSE;
		JogBw[0]:=FALSE;JogBw[1]:=FALSE;JogBw[2]:=FALSE;JogBw[3]:=FALSE;JogBw[4]:=FALSE;JogBw[5]:=FALSE;
		Move_JOG();//失能功能块
		
		AxisMoveTrigger[0]:=FALSE;AxisMoveTrigger[1]:=FALSE;AxisMoveTrigger[2]:=FALSE;
		AxisMoveTrigger[3]:=FALSE;AxisMoveTrigger[4]:=FALSE;AxisMoveTrigger[5]:=FALSE;
		AxisMoveAbsoulte();//失能功能块
		
		Home[0]:=FALSE;Home[1]:=FALSE;Home[2]:=FALSE;
		Home[3]:=FALSE;Home[4]:=FALSE;Home[5]:=FALSE;
		Homing();//失能功能块	

		AxisResetTrigger[0]:=FALSE;AxisResetTrigger[1]:=FALSE;AxisResetTrigger[2]:=FALSE;
		AxisResetTrigger[3]:=FALSE;AxisResetTrigger[4]:=FALSE;AxisResetTrigger[5]:=FALSE;
		AxisReset();//失能功能块
		
		P_TextModeWrite_WriteTrigger:=FALSE;
		P_TextModeWrite();	
		P_TextModeRead_ReadTrigger:=FALSE;
		P_TextModeRead();//失能功能块
		
		SetPointGenEnable[0].Execute:=FALSE;SetPointGenEnable[1].Execute:=FALSE;
		SetPointGenEnable[2].Execute:=FALSE;SetPointGenEnable[3].Execute:=FALSE;
		SetPointGenEnable[4].Execute:=FALSE;SetPointGenEnable[5].Execute:=FALSE;

		SetPointGenDisable[0].Execute:=FALSE;SetPointGenDisable[1].Execute:=FALSE;		
		SetPointGenDisable[2].Execute:=FALSE;SetPointGenDisable[3].Execute:=FALSE;		
		SetPointGenDisable[4].Execute:=FALSE;SetPointGenDisable[5].Execute:=FALSE;		
		setpositionGen();
		
		JogMode[0]:=MC_JOGMODE_STANDARD_FAST;
		JogMode[1]:=MC_JOGMODE_STANDARD_FAST;
		JogMode[2]:=MC_JOGMODE_STANDARD_FAST;
		JogMode[3]:=MC_JOGMODE_STANDARD_FAST;
		JogMode[4]:=MC_JOGMODE_STANDARD_FAST;
		JogMode[5]:=MC_JOGMODE_STANDARD_FAST;
		
		GVL.PosRun := FALSE;
		GVL.TrajRun:= FALSE;
		CurrentJobState:='Wait Command';
	1://SetZero
		Home[0]:=TRUE;Home[1]:=TRUE;Home[2]:=TRUE;
		Home[3]:=TRUE;Home[4]:=TRUE;Home[5]:=TRUE;
		Home_Mode[0]:=MC_Direct;Home_Mode[1]:=MC_Direct;Home_Mode[2]:=MC_Direct;
		Home_Mode[3]:=MC_Direct;Home_Mode[4]:=MC_Direct;Home_Mode[5]:=MC_Direct;
		Home_Pos[0]:=0;Home_Pos[1]:=0;Home_Pos[2]:=0;
		Home_Pos[3]:=0;Home_Pos[4]:=0;Home_Pos[5]:=0;
		Homing();

		IF Home_Done[0]=TRUE AND 
		   Home_Done[1]=TRUE AND 
		   Home_Done[2]=TRUE AND 
		   Home_Done[3]=TRUE AND 
		   Home_Done[4]=TRUE AND 
		   Home_Done[5]=TRUE THEN
			CurrentJob:=0;
			CurrentJobState:='Set Origin Done!';
		ELSE
			CurrentJobState:='Set Origin Doing';
		END_IF
	2://直线插补
		setpointgenenable[0].Execute:=TRUE;setpointgenenable[1].Execute:=TRUE;
		setpointgenenable[2].Execute:=TRUE;setpointgenenable[3].Execute:=TRUE;
		setpointgenenable[4].Execute:=TRUE;setpointgenenable[5].Execute:=TRUE;
		IF  SetPointGenEnable[0].Enabled AND
			SetPointGenEnable[1].Enabled AND
			SetPointGenEnable[2].Enabled AND
			SetPointGenEnable[3].Enabled AND
			SetPointGenEnable[4].Enabled AND
			SetPointGenEnable[5].Enabled THEN
			GVL.PosRun := TRUE;	
			
			IF(GVL.ExtPosOK = TRUE) THEN
				CurrentJob:=0;
			END_IF
			
			MC_ExtSetPointGenFeed(Position:=ExtPos[0],//Position:= Pos[i,5],//STRING_TO_LREAL(P_TextModeRead.database[i,5]),
				Velocity:= 0,Acceleration:=0,Direction:=1,Axis:=Axis[0]);
				
			MC_ExtSetPointGenFeed(Position:=-ExtPos[1],//Position:= Pos[i,4],//STRING_TO_LREAL(P_TextModeRead.database[i,4]),
				Velocity:= 0,Acceleration:=0,Direction:=1,Axis:=Axis[1]);
				
			MC_ExtSetPointGenFeed(Position:=ExtPos[2],//Position:= Pos[i,3],//STRING_TO_LREAL(P_TextModeRead.database[i,3]),
				Velocity:= 0,Acceleration:=0,Direction:=1,Axis:=Axis[2]);
				
			MC_ExtSetPointGenFeed(Position:=ExtPos[3],//Position:= Pos[i,2],//STRING_TO_LREAL(P_TextModeRead.database[i,2]),
				Velocity:= 0,Acceleration:=0,Direction:=1,Axis:=Axis[3]);
				
			MC_ExtSetPointGenFeed(Position:=ExtPos[4],//Position:= Pos[i,1],//STRING_TO_LREAL(P_TextModeRead.database[i,1]),
				Velocity:= 0,Acceleration:=0,Direction:=1,Axis:=Axis[4]);
				
			MC_ExtSetPointGenFeed(Position:=ExtPos[5],//Position:= Pos[i,0],//STRING_TO_LREAL(P_TextModeRead.database[i,0]),
				Velocity:= 0,Acceleration:=0,Direction:=1,Axis:=Axis[5]);
		END_IF
		setpositionGen();
	3://JogForward
		JogFw[axisNum]:=TRUE;
		Move_JOG();
		CurrentJob:=3;
		CurrentJobState:='Jog Forward';
	4://JogBackward
		JogBw[axisNum]:=TRUE;
		Move_JOG();
		CurrentJob:=4;
		CurrentJobState:='Jog Backward';
	5://Stop
		AxisStopDeceleration[0]:=15000;AxisStopDeceleration[1]:=15000;AxisStopDeceleration[2]:=15000;
		AxisStopDeceleration[3]:=15000;AxisStopDeceleration[4]:=15000;AxisStopDeceleration[5]:=15000;
		AxisStopTrigger[0]:=TRUE;AxisStopTrigger[1]:=TRUE;AxisStopTrigger[2]:=TRUE;
		AxisStopTrigger[3]:=TRUE;AxisStopTrigger[4]:=TRUE;AxisStopTrigger[5]:=TRUE;
		AxisStop();
		IF AxisStopDone[0]=TRUE AND
		   AxisStopDone[1]=TRUE AND
		   AxisStopDone[2]=TRUE AND
		   AxisStopDone[3]=TRUE AND
		   AxisStopDone[4]=TRUE AND
		   AxisStopDone[5]=TRUE THEN
			CurrentJobState:='Stop Done';
			CurrentJob:=0;
		ELSE
			CurrentJobState:='Stop Doing';
		END_IF
	6://Move To HOME
		AxisMovePosition[0]:=-742579.6646;AxisMovePosition[1]:=5125.997925;AxisMovePosition[2]:=223.8519;
		AxisMovePosition[3]:=5161.5829;AxisMovePosition[4]:=-31.9675;AxisMovePosition[5]:=774.2587;	
		AxisMoveSpeed[0]:=2000;AxisMoveSpeed[1]:=2000;AxisMoveSpeed[2]:=2000;
		AxisMoveSpeed[3]:=2000;AxisMoveSpeed[4]:=2000;AxisMoveSpeed[5]:=2000;
		
		AxisMoveTrigger[0]:=TRUE;AxisMoveTrigger[1]:=TRUE;AxisMoveTrigger[2]:=TRUE;
		AxisMoveTrigger[3]:=TRUE;AxisMoveTrigger[4]:=TRUE;AxisMoveTrigger[5]:=TRUE;
		AxisMoveAbsoulte();
		
		IF AxisMoveAbsoluteDone[0]=TRUE AND 
		   AxisMoveAbsoluteDone[1]=TRUE AND 
		   AxisMoveAbsoluteDone[2]=TRUE AND 
		   AxisMoveAbsoluteDone[3]=TRUE AND 
		   AxisMoveAbsoluteDone[4]=TRUE AND 
		   AxisMoveAbsoluteDone[5]=TRUE THEN			
			CurrentJobState:='Home Done';
			CurrentJob:=1;			
		ELSE
			CurrentJobState:='Home Doing';
		END_IF
	7://Move To A
		AxisMovePosition[0]:=MoveA[0];AxisMovePosition[1]:=MoveA[1];AxisMovePosition[2]:=MoveA[2];
		AxisMovePosition[3]:=MoveA[3];AxisMovePosition[4]:=MoveA[4];AxisMovePosition[5]:=MoveA[5];
		
		AxisMoveSpeed[0]:=GlobalSetSpeed[0];AxisMoveSpeed[1]:=GlobalSetSpeed[1];AxisMoveSpeed[2]:=GlobalSetSpeed[2];
		AxisMoveSpeed[3]:=GlobalSetSpeed[3];AxisMoveSpeed[4]:=GlobalSetSpeed[4];AxisMoveSpeed[5]:=GlobalSetSpeed[5];
		
		AxisMoveTrigger[0]:=TRUE;AxisMoveTrigger[1]:=TRUE;AxisMoveTrigger[2]:=TRUE;
		AxisMoveTrigger[3]:=TRUE;AxisMoveTrigger[4]:=TRUE;AxisMoveTrigger[5]:=TRUE;
		AxisMoveAbsoulte();
		
		IF AxisMoveAbsoluteDone[0]=TRUE AND 
		   AxisMoveAbsoluteDone[1]=TRUE AND 
		   AxisMoveAbsoluteDone[2]=TRUE AND 
		   AxisMoveAbsoluteDone[3]=TRUE AND 
		   AxisMoveAbsoluteDone[4]=TRUE AND 
		   AxisMoveAbsoluteDone[5]=TRUE THEN		
			CurrentJobState:='MOVE A Done';
			CurrentJob:=0;		
		ELSE
			CurrentJobState:='MOVE A Doing';
		END_IF
	8://往复运动
		IF Move_AB=FALSE THEN
		//AxisMovePosition[0]:=-742579.6646;AxisMovePosition[1]:=5125.997925;AxisMovePosition[2]:=223.8519;
		//AxisMovePosition[3]:=5161.5829;AxisMovePosition[4]:=-31.9675;AxisMovePosition[5]:=774.2587;	
		AxisMovePosition[0]:=0;AxisMovePosition[1]:=0;AxisMovePosition[2]:=0;
		AxisMovePosition[3]:=0;AxisMovePosition[4]:=0;AxisMovePosition[5]:=0;
		ELSE
		AxisMovePosition[0]:=MoveA[0];AxisMovePosition[1]:=MoveA[1];AxisMovePosition[2]:=MoveA[2];
		AxisMovePosition[3]:=MoveA[3];AxisMovePosition[4]:=MoveA[4];AxisMovePosition[5]:=MoveA[5];	
		END_IF
		AxisMoveSpeed[0]:=2000;AxisMoveSpeed[1]:=2000;AxisMoveSpeed[2]:=2000;
		AxisMoveSpeed[3]:=2000;AxisMoveSpeed[4]:=2000;AxisMoveSpeed[5]:=2000;
		
		AxisMoveTrigger[0]:=TRUE;AxisMoveTrigger[1]:=TRUE;AxisMoveTrigger[2]:=TRUE;
		AxisMoveTrigger[3]:=TRUE;AxisMoveTrigger[4]:=TRUE;AxisMoveTrigger[5]:=TRUE;
		AxisMoveAbsoulte();
		
		IF AxisMoveAbsoluteDone[0]=TRUE AND 
		   AxisMoveAbsoluteDone[1]=TRUE AND 
		   AxisMoveAbsoluteDone[2]=TRUE AND 
		   AxisMoveAbsoluteDone[3]=TRUE AND 
		   AxisMoveAbsoluteDone[4]=TRUE AND 
		   AxisMoveAbsoluteDone[5]=TRUE THEN	
		   Move_AB:= NOT Move_AB;
		   AxisMoveTrigger[0]:=FALSE;AxisMoveTrigger[1]:=FALSE;AxisMoveTrigger[2]:=FALSE;
		   AxisMoveTrigger[3]:=FALSE;AxisMoveTrigger[4]:=FALSE;AxisMoveTrigger[5]:=FALSE;
		   AxisMoveAbsoulte();//失能功能块
		END_IF
		CurrentJobState:='Reciprocating Doing';
	9://复位
		AxisResetTrigger[0]:=TRUE;AxisResetTrigger[1]:=TRUE;AxisResetTrigger[2]:=TRUE;
		AxisResetTrigger[3]:=TRUE;AxisResetTrigger[4]:=TRUE;AxisResetTrigger[5]:=TRUE;
		AxisReset();
		IF AxisResetDone[0]=TRUE AND
		   AxisResetDone[1]=TRUE AND
		   AxisResetDone[2]=TRUE AND
		   AxisResetDone[3]=TRUE AND
		   AxisResetDone[4]=TRUE AND
		   AxisResetDone[5]=TRUE THEN	
			CurrentJobState:='Axis Reset Done';
			CurrentJob:=0;
		ELSE
			CurrentJobState:='Axis Reset Doing';
		END_IF
	10://read csv
		//P_TextModeRead_ReadTrigger:=TRUE;
		//CurrentJobState:='Read CSV';
		//P_TextModeRead();
		GVL.TrajRun:= TRUE;	
		CurrentJob:=0;
	11://Move to origin
		AxisMovePosition[0]:=0;AxisMovePosition[1]:=0;AxisMovePosition[2]:=0;
		AxisMovePosition[3]:=0;AxisMovePosition[4]:=0;AxisMovePosition[5]:=0;
		
		AxisMoveSpeed[0]:=2000;AxisMoveSpeed[1]:=2000;AxisMoveSpeed[2]:=2000;
		AxisMoveSpeed[3]:=2000;AxisMoveSpeed[4]:=2000;AxisMoveSpeed[5]:=2000;
		
		AxisMoveTrigger[0]:=TRUE;AxisMoveTrigger[1]:=TRUE;AxisMoveTrigger[2]:=TRUE;
		AxisMoveTrigger[3]:=TRUE;AxisMoveTrigger[4]:=TRUE;AxisMoveTrigger[5]:=TRUE;
		AxisMoveAbsoulte();
		
		IF AxisMoveAbsoluteDone[0]=TRUE AND 
		   AxisMoveAbsoluteDone[1]=TRUE AND 
		   AxisMoveAbsoluteDone[2]=TRUE AND 
		   AxisMoveAbsoluteDone[3]=TRUE AND 
		   AxisMoveAbsoluteDone[4]=TRUE AND 
		   AxisMoveAbsoluteDone[5]=TRUE THEN		
			CurrentJobState:='MOVE Origin Done';
			CurrentJob:=0;		
		ELSE
			CurrentJobState:='MOVE Origin Doing';
		END_IF
END_CASE

//错误检测
IF  AxisPowerError[0] OR
	AxisPowerError[1] OR
	AxisPowerError[2] OR
	AxisPowerError[3] OR
	AxisPowerError[4] OR
	AxisPowerError[5] THEN
	//POWER:=FALSE;
	CurrentJob:=9;
END_IF
//电机上下电
IF POWER=TRUE THEN
	AxisPowerTrigger[0]:=TRUE;
	AxisPowerTrigger[1]:=TRUE;
	AxisPowerTrigger[2]:=TRUE;
	AxisPowerTrigger[3]:=TRUE;
	AxisPowerTrigger[4]:=TRUE;
	AxisPowerTrigger[5]:=TRUE;
	AxisEnable();
	IF  AxisPowerReady[0]=TRUE AND 
		AxisPowerReady[1]=TRUE AND 
		AxisPowerReady[2]=TRUE AND 
		AxisPowerReady[3]=TRUE AND
		AxisPowerReady[4]=TRUE AND 
		AxisPowerReady[5]=TRUE THEN
		LAMP:=TRUE;
	END_IF
ELSE
	AxisPowerTrigger[0]:=FALSE;
	AxisPowerTrigger[1]:=FALSE;
	AxisPowerTrigger[2]:=FALSE;
	AxisPowerTrigger[3]:=FALSE;
	AxisPowerTrigger[4]:=FALSE;
	AxisPowerTrigger[5]:=FALSE;
	AxisEnable();
	IF  AxisPowerReady[0]=FALSE AND
		AxisPowerReady[1]=FALSE AND
		AxisPowerReady[2]=FALSE AND
		AxisPowerReady[3]=FALSE AND
		AxisPowerReady[4]=FALSE AND
		AxisPowerReady[5]=FALSE THEN
		LAMP:=FALSE;   
	END_IF
END_IF]]></ST>
    </Implementation>
    <Action Name="setpositionGen" Id="{ae6c9d44-33f1-4fe3-8a12-7ba33d831292}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenEnable_output[0].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">31L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenEnable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenEnable[0]"</v>
                            <v n="Type">"MC_ExtSetPointGenEnable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">8L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[0].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">10L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[0].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">11L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[0].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">12L</v>
                              </o>
                              <o>
                                <v n="Operand">"enable[0]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">13L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[0]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">5L</v>
                              </o>
                              <v n="Id">4L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[0].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">7L</v>
                              </o>
                              <v n="Id">6L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[0].Position"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">15L</v>
                              </o>
                              <v n="Id">14L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[0].PositionType"</v>
                                <v n="Type">"E_PositionType"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">17L</v>
                              </o>
                              <v n="Id">16L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                              <v>Position</v>
                              <v>PositionType</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                              <v>LREAL</v>
                              <v>E_PositionType</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">9L</v>
                        </o>
                        <v n="Id">32L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenDisable_output[0].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">33L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenDisable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenDisable[0]"</v>
                            <v n="Type">"MC_ExtSetpointGenDisable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">25L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[0].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">27L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[0].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">28L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[0].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">29L</v>
                              </o>
                              <o>
                                <v n="Operand">"disable[0]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">30L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[0]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">22L</v>
                              </o>
                              <v n="Id">21L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgendisable[0].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">24L</v>
                              </o>
                              <v n="Id">23L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">26L</v>
                        </o>
                        <v n="Id">34L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">18L</v>
                  </o>
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenEnable_output[1].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">50L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenEnable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenEnable[1]"</v>
                            <v n="Type">"MC_ExtSetPointGenEnable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">36L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[1].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">38L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[1].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">39L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[1].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">40L</v>
                              </o>
                              <o>
                                <v n="Operand">"enable[1]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">41L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[1]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">43L</v>
                              </o>
                              <v n="Id">42L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[1].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">45L</v>
                              </o>
                              <v n="Id">44L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[1].Position"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">47L</v>
                              </o>
                              <v n="Id">46L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[1].PositionType"</v>
                                <v n="Type">"E_PositionType"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">49L</v>
                              </o>
                              <v n="Id">48L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                              <v>Position</v>
                              <v>PositionType</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                              <v>LREAL</v>
                              <v>E_PositionType</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">37L</v>
                        </o>
                        <v n="Id">51L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">35L</v>
                  </o>
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenDisable_output[1].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">63L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenDisable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenDisable[1]"</v>
                            <v n="Type">"MC_ExtSetpointGenDisable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">53L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[1].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">55L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[1].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">56L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[1].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">57L</v>
                              </o>
                              <o>
                                <v n="Operand">"disable[1]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">58L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[1]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">60L</v>
                              </o>
                              <v n="Id">59L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgendisable[1].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">62L</v>
                              </o>
                              <v n="Id">61L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">54L</v>
                        </o>
                        <v n="Id">64L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">52L</v>
                  </o>
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenEnable_output[2].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">80L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenEnable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenEnable[2]"</v>
                            <v n="Type">"MC_ExtSetPointGenEnable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">66L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[2].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">68L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[2].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">69L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[2].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">70L</v>
                              </o>
                              <o>
                                <v n="Operand">"enable[2]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">71L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[2]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">73L</v>
                              </o>
                              <v n="Id">72L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[2].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">75L</v>
                              </o>
                              <v n="Id">74L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[2].Position"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">77L</v>
                              </o>
                              <v n="Id">76L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[2].PositionType"</v>
                                <v n="Type">"E_PositionType"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">79L</v>
                              </o>
                              <v n="Id">78L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                              <v>Position</v>
                              <v>PositionType</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                              <v>LREAL</v>
                              <v>E_PositionType</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">67L</v>
                        </o>
                        <v n="Id">81L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">65L</v>
                  </o>
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenDisable_output[2].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">93L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenDisable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenDisable[2]"</v>
                            <v n="Type">"MC_ExtSetpointGenDisable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">83L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[2].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">85L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[2].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">86L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[2].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">87L</v>
                              </o>
                              <o>
                                <v n="Operand">"disable[2]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">88L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[2]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">90L</v>
                              </o>
                              <v n="Id">89L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgendisable[2].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">92L</v>
                              </o>
                              <v n="Id">91L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">84L</v>
                        </o>
                        <v n="Id">94L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">82L</v>
                  </o>
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenEnable_output[3].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">110L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenEnable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenEnable[3]"</v>
                            <v n="Type">"MC_ExtSetPointGenEnable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">96L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[3].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">98L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[3].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">99L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[3].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">100L</v>
                              </o>
                              <o>
                                <v n="Operand">"enable[3]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">101L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[3]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">103L</v>
                              </o>
                              <v n="Id">102L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[3].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">105L</v>
                              </o>
                              <v n="Id">104L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[3].Position"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">107L</v>
                              </o>
                              <v n="Id">106L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[3].PositionType"</v>
                                <v n="Type">"E_PositionType"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">109L</v>
                              </o>
                              <v n="Id">108L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                              <v>Position</v>
                              <v>PositionType</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                              <v>LREAL</v>
                              <v>E_PositionType</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">97L</v>
                        </o>
                        <v n="Id">111L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">95L</v>
                  </o>
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenDisable_output[3].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">123L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenDisable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenDisable[3]"</v>
                            <v n="Type">"MC_ExtSetpointGenDisable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">113L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[3].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">115L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[3].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">116L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[3].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">117L</v>
                              </o>
                              <o>
                                <v n="Operand">"disable[3]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">118L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[3]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">120L</v>
                              </o>
                              <v n="Id">119L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgendisable[3].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">122L</v>
                              </o>
                              <v n="Id">121L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">114L</v>
                        </o>
                        <v n="Id">124L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">112L</v>
                  </o>
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenEnable_output[4].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">140L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenEnable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenEnable[4]"</v>
                            <v n="Type">"MC_ExtSetPointGenEnable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">126L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[4].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">128L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[4].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">129L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[4].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">130L</v>
                              </o>
                              <o>
                                <v n="Operand">"enable[4]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">131L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[4]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">133L</v>
                              </o>
                              <v n="Id">132L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[4].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">135L</v>
                              </o>
                              <v n="Id">134L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[4].Position"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">137L</v>
                              </o>
                              <v n="Id">136L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[4].PositionType"</v>
                                <v n="Type">"E_PositionType"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">139L</v>
                              </o>
                              <v n="Id">138L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                              <v>Position</v>
                              <v>PositionType</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                              <v>LREAL</v>
                              <v>E_PositionType</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">127L</v>
                        </o>
                        <v n="Id">141L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">125L</v>
                  </o>
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenDisable_output[4].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">153L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenDisable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenDisable[4]"</v>
                            <v n="Type">"MC_ExtSetpointGenDisable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">143L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[4].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">145L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[4].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">146L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[4].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">147L</v>
                              </o>
                              <o>
                                <v n="Operand">"disable[4]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">148L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[4]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">150L</v>
                              </o>
                              <v n="Id">149L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgendisable[4].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">152L</v>
                              </o>
                              <v n="Id">151L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">144L</v>
                        </o>
                        <v n="Id">154L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">142L</v>
                  </o>
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenEnable_output[5].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">170L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenEnable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenEnable[5]"</v>
                            <v n="Type">"MC_ExtSetPointGenEnable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">156L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[5].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">158L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[5].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">159L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenEnable_output[5].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">160L</v>
                              </o>
                              <o>
                                <v n="Operand">"enable[5]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">161L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[5]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">163L</v>
                              </o>
                              <v n="Id">162L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[5].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">165L</v>
                              </o>
                              <v n="Id">164L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[5].Position"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">167L</v>
                              </o>
                              <v n="Id">166L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgenenable[5].PositionType"</v>
                                <v n="Type">"E_PositionType"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">169L</v>
                              </o>
                              <v n="Id">168L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                              <v>Position</v>
                              <v>PositionType</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                              <v>LREAL</v>
                              <v>E_PositionType</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">157L</v>
                        </o>
                        <v n="Id">171L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">155L</v>
                  </o>
                  <o>
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"SetPointGenDisable_output[5].Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">183L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_ExtSetPointGenDisable"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SetPointGenDisable[5]"</v>
                            <v n="Type">"MC_ExtSetpointGenDisable"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">173L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[5].Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">175L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[5].Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">176L</v>
                              </o>
                              <o>
                                <v n="Operand">"SetPointGenDisable_output[5].ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">177L</v>
                              </o>
                              <o>
                                <v n="Operand">"disable[5]"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">178L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Axis[5]"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">"Axis Bind link"</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">180L</v>
                              </o>
                              <v n="Id">179L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"setpointgendisable[5].Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">182L</v>
                              </o>
                              <v n="Id">181L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Axis</v>
                              <v>Execute</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                              <v>Enabled</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="Id">174L</v>
                        </o>
                        <v n="Id">184L</v>
                      </o>
                    </l2>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <l2 n="Connectors" />
                    <v n="Id">172L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
  </POU>
</TcPlcObject>